import type {
  CourseAssessment,
} from "./types";


export const pythonForDataAnalysisAssessments:
  CourseAssessment[] = [

  {
    key: "module-01-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 1,
    title: "Module 1 Checkpoint",
    description: "Check your understanding of python foundations for analysis.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m1-l1-q1",
        question: "What should usually happen before calculating a business KPI from a new file?",
        options: [
          "Plot immediately",
          "Audit structure and quality",
          "Rename every column",
          "Delete missing rows",
        ],
        correctIndex: 1,
        explanation: "You need to understand the data before trusting a calculation.",
      },
      {
        id: "py-m1-l1-q2",
        question: "A reproducible notebook should ideally...",
        options: [
          "Depend on cells run in random order",
          "Run from top to bottom",
          "Overwrite the raw file",
          "Contain only charts",
        ],
        correctIndex: 1,
        explanation: "Top-to-bottom execution reduces hidden state.",
      },
      {
        id: "py-m1-l2-q1",
        question: "Which collection stores key-value pairs?",
        options: [
          "list",
          "dict",
          "tuple",
          "set",
        ],
        correctIndex: 1,
        explanation: "A dictionary maps keys to values.",
      },
      {
        id: "py-m1-l2-q2",
        question: "What is type('12')?",
        options: [
          "int",
          "float",
          "str",
          "bool",
        ],
        correctIndex: 2,
        explanation: "Quotes create a string.",
      },
      {
        id: "py-m1-l3-q1",
        question: "What should a reusable calculation function usually do with its result?",
        options: [
          "Only print it",
          "Return it",
          "Store it globally",
          "Write it to raw data",
        ],
        correctIndex: 1,
        explanation: "Returned values are reusable and testable.",
      },
      {
        id: "py-m1-l3-q2",
        question: "Which construct handles alternative logical branches?",
        options: [
          "import",
          "if/elif/else",
          "class only",
          "with only",
        ],
        correctIndex: 1,
        explanation: "Conditional branches control which block runs.",
      },
      {
        id: "py-m1-l4-q1",
        question: "Which variable name is clearest?",
        options: [
          "x1",
          "tmp",
          "monthly_revenue",
          "v",
        ],
        correctIndex: 2,
        explanation: "The name communicates analytical meaning.",
      },
      {
        id: "py-m1-l4-q2",
        question: "What is a useful role for assert in analysis code?",
        options: [
          "Styling charts",
          "Checking assumptions",
          "Installing packages",
          "Reading only JSON",
        ],
        correctIndex: 1,
        explanation: "Assertions make assumptions executable.",
      },
    ],
  },

  {
    key: "module-02-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 2,
    title: "Module 2 Checkpoint",
    description: "Check your understanding of numpy for numerical work.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m2-l1-q1",
        question: "Which library provides ndarray?",
        options: [
          "pandas",
          "NumPy",
          "pathlib",
          "json",
        ],
        correctIndex: 1,
        explanation: "NumPy provides ndarray.",
      },
      {
        id: "py-m2-l1-q2",
        question: "What does x*2 do for a numeric NumPy array?",
        options: [
          "Duplicates the object reference",
          "Multiplies each element by 2",
          "Adds two rows",
          "Converts to a list",
        ],
        correctIndex: 1,
        explanation: "Arithmetic is vectorised element-wise.",
      },
      {
        id: "py-m2-l2-q1",
        question: "A Boolean mask is primarily used to...",
        options: [
          "Rename variables",
          "Filter elements by condition",
          "Read files",
          "Sort dictionaries",
        ],
        correctIndex: 1,
        explanation: "Masks select elements where the condition is True.",
      },
      {
        id: "py-m2-l2-q2",
        question: "What does x[:, 1] mean for a matrix?",
        options: [
          "Second row",
          "All rows, second column",
          "First column",
          "Every second element only",
        ],
        correctIndex: 1,
        explanation: "Colon selects all rows and 1 selects the second column.",
      },
      {
        id: "py-m2-l3-q1",
        question: "Which function ignores NaN values when calculating a mean?",
        options: [
          "np.mean",
          "np.nanmean",
          "np.array",
          "np.shape",
        ],
        correctIndex: 1,
        explanation: "np.nanmean is NaN-aware.",
      },
      {
        id: "py-m2-l3-q2",
        question: "For a rows-by-columns matrix, mean(axis=0) returns...",
        options: [
          "One mean per column",
          "One mean per row",
          "One global mean only",
          "No result",
        ],
        correctIndex: 0,
        explanation: "axis=0 collapses rows.",
      },
      {
        id: "py-m2-l4-q1",
        question: "Which object is recommended for modern NumPy random generation?",
        options: [
          "np.random.default_rng()",
          "open()",
          "pd.Series()",
          "Path()",
        ],
        correctIndex: 0,
        explanation: "default_rng creates a Generator.",
      },
      {
        id: "py-m2-l4-q2",
        question: "A fixed seed mainly supports...",
        options: [
          "Faster internet",
          "Reproducibility",
          "Automatic normality",
          "Missing-value removal",
        ],
        correctIndex: 1,
        explanation: "The pseudo-random sequence becomes repeatable.",
      },
    ],
  },

  {
    key: "module-03-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 3,
    title: "Module 3 Checkpoint",
    description: "Check your understanding of pandas foundations.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m3-l1-q1",
        question: "Which object is two-dimensional?",
        options: [
          "Series",
          "DataFrame",
          "set",
          "Path",
        ],
        correctIndex: 1,
        explanation: "A DataFrame is a labelled 2D table.",
      },
      {
        id: "py-m3-l1-q2",
        question: "Which accessor selects by integer position?",
        options: [
          "loc",
          "iloc",
          "groupby",
          "merge",
        ],
        correctIndex: 1,
        explanation: "iloc is position-based.",
      },
      {
        id: "py-m3-l2-q1",
        question: "Which operator combines two pandas Boolean conditions with logical AND?",
        options: [
          "and",
          "&&",
          "&",
          "+",
        ],
        correctIndex: 2,
        explanation: "Use element-wise & with parentheses.",
      },
      {
        id: "py-m3-l2-q2",
        question: "What does ascending=False do in sort_values?",
        options: [
          "Sorts largest to smallest",
          "Drops missing values",
          "Reverses column order only",
          "Converts to string",
        ],
        correctIndex: 0,
        explanation: "False requests descending order.",
      },
      {
        id: "py-m3-l3-q1",
        question: "Which method is useful for adding columns in a pipeline?",
        options: [
          "assign",
          "head",
          "merge only",
          "shape",
        ],
        correctIndex: 0,
        explanation: "assign returns a DataFrame with new columns.",
      },
      {
        id: "py-m3-l3-q2",
        question: "Series.map is especially useful for...",
        options: [
          "Category lookup/relabeling",
          "Reading CSV files",
          "Changing row order",
          "Computing matrix inverses",
        ],
        correctIndex: 0,
        explanation: "map applies a lookup/function to values.",
      },
      {
        id: "py-m3-l4-q1",
        question: "Which function converts a column to numeric with controlled parsing?",
        options: [
          "pd.to_numeric",
          "df.plot",
          "np.merge",
          "Path.rename",
        ],
        correctIndex: 0,
        explanation: "to_numeric handles numeric conversion.",
      },
      {
        id: "py-m3-l4-q2",
        question: "What does pd.to_datetime create conceptually?",
        options: [
          "Datetime-like values",
          "Only strings",
          "Sets",
          "Boolean masks only",
        ],
        correctIndex: 0,
        explanation: "It parses date/time values.",
      },
    ],
  },

  {
    key: "module-04-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 4,
    title: "Module 4 Checkpoint",
    description: "Check your understanding of cleaning and reshaping data.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m4-l1-q1",
        question: "Which expression estimates missing proportion by column?",
        options: [
          "df.isna().mean()",
          "df.mean().isna()",
          "df.shape only",
          "df.sort_values()",
        ],
        correctIndex: 0,
        explanation: "Boolean missing indicators average to proportions.",
      },
      {
        id: "py-m4-l1-q2",
        question: "Complete-case deletion should usually be defined using...",
        options: [
          "All columns automatically",
          "Variables required for the analysis",
          "Only text columns",
          "The index",
        ],
        correctIndex: 1,
        explanation: "Completeness should match the analytical variables.",
      },
      {
        id: "py-m4-l2-q1",
        question: "Which pandas accessor exposes vectorised string methods?",
        options: [
          ".str",
          ".num",
          ".txt",
          ".cat only",
        ],
        correctIndex: 0,
        explanation: "Series.str provides string operations.",
      },
      {
        id: "py-m4-l2-q2",
        question: "Why can inconsistent case affect groupby?",
        options: [
          "Equivalent labels become separate groups",
          "It changes numeric values",
          "It deletes rows",
          "It alters file paths only",
        ],
        correctIndex: 0,
        explanation: "Grouping uses exact values.",
      },
      {
        id: "py-m4-l3-q1",
        question: "A statistically extreme observation should be...",
        options: [
          "Deleted automatically",
          "Investigated before action",
          "Set to the mean",
          "Converted to string",
        ],
        correctIndex: 1,
        explanation: "Extremeness alone does not prove error.",
      },
      {
        id: "py-m4-l3-q2",
        question: "Which property checks identifier uniqueness?",
        options: [
          "is_unique",
          "isna only",
          "dtype",
          "shape",
        ],
        correctIndex: 0,
        explanation: "is_unique reports whether values are unique.",
      },
      {
        id: "py-m4-l4-q1",
        question: "In tidy data, one variable usually corresponds to...",
        options: [
          "One column",
          "One file only",
          "One plot",
          "One function",
        ],
        correctIndex: 0,
        explanation: "Tidy data places variables in columns.",
      },
      {
        id: "py-m4-l4-q2",
        question: "Which method converts wide columns into rows?",
        options: [
          "melt",
          "merge",
          "sort_values",
          "describe",
        ],
        correctIndex: 0,
        explanation: "melt performs wide-to-long reshaping.",
      },
    ],
  },

  {
    key: "module-05-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 5,
    title: "Module 5 Checkpoint",
    description: "Check your understanding of grouping and combining data.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m5-l1-q1",
        question: "Which method creates grouped calculations?",
        options: [
          "groupby",
          "merge",
          "melt",
          "read_csv",
        ],
        correctIndex: 0,
        explanation: "groupby performs split-apply-combine.",
      },
      {
        id: "py-m5-l1-q2",
        question: "Why report n with a group mean?",
        options: [
          "To provide sample-size context",
          "To change the mean",
          "To remove missingness",
          "To create dates",
        ],
        correctIndex: 0,
        explanation: "Group size affects interpretation.",
      },
      {
        id: "py-m5-l2-q1",
        question: "Which function is designed for categorical frequency tables?",
        options: [
          "pd.crosstab",
          "pd.read_csv",
          "np.mean",
          "Path",
        ],
        correctIndex: 0,
        explanation: "crosstab summarises categorical combinations.",
      },
      {
        id: "py-m5-l2-q2",
        question: "normalize='index' produces...",
        options: [
          "Row proportions",
          "Column names",
          "Raw means only",
          "Missing counts",
        ],
        correctIndex: 0,
        explanation: "It normalises within each row.",
      },
      {
        id: "py-m5-l3-q1",
        question: "Which join keeps every row from the left table?",
        options: [
          "inner",
          "left",
          "right only",
          "cross only",
        ],
        correctIndex: 1,
        explanation: "A left join preserves left rows.",
      },
      {
        id: "py-m5-l3-q2",
        question: "Which argument can enforce expected key cardinality?",
        options: [
          "validate",
          "ascending",
          "dtype",
          "usecols",
        ],
        correctIndex: 0,
        explanation: "validate checks merge relationships.",
      },
      {
        id: "py-m5-l4-q1",
        question: "Which method usually returns the same number of rows as the input?",
        options: [
          "agg",
          "transform",
          "groupby.size only",
          "pivot_table always",
        ],
        correctIndex: 1,
        explanation: "transform aligns group results to original rows.",
      },
      {
        id: "py-m5-l4-q2",
        question: "A rolling window is useful for...",
        options: [
          "Local moving summaries",
          "Merging files",
          "Changing dtypes only",
          "Creating dictionaries",
        ],
        correctIndex: 0,
        explanation: "Rolling operations summarise nearby observations.",
      },
    ],
  },

  {
    key: "module-06-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 6,
    title: "Module 6 Checkpoint",
    description: "Check your understanding of exploratory analysis and visualisation.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m6-l1-q1",
        question: "Which summary is often robust to a long right tail?",
        options: [
          "Median",
          "Maximum only",
          "ID mean",
          "File size",
        ],
        correctIndex: 0,
        explanation: "Median is less influenced by extreme values.",
      },
      {
        id: "py-m6-l1-q2",
        question: "EDA is primarily used to...",
        options: [
          "Understand structure and patterns",
          "Prove causality automatically",
          "Eliminate all uncertainty",
          "Replace data cleaning",
        ],
        correctIndex: 0,
        explanation: "EDA characterises the observed data.",
      },
      {
        id: "py-m6-l2-q1",
        question: "Which plot is most suitable for two numeric variables?",
        options: [
          "Scatter plot",
          "Pie chart always",
          "Table only",
          "Histogram of labels",
        ],
        correctIndex: 0,
        explanation: "Scatter plots show paired numeric relationships.",
      },
      {
        id: "py-m6-l2-q2",
        question: "A line plot is particularly useful when the x-axis is...",
        options: [
          "Ordered, often time",
          "An unordered ID only",
          "A file path",
          "A Python function",
        ],
        correctIndex: 0,
        explanation: "Lines imply an ordered sequence.",
      },
      {
        id: "py-m6-l3-q1",
        question: "A correlation coefficient primarily summarises...",
        options: [
          "Linear association",
          "Causal effect",
          "Missingness only",
          "File size",
        ],
        correctIndex: 0,
        explanation: "Correlation is a measure of linear association.",
      },
      {
        id: "py-m6-l3-q2",
        question: "A single extreme point can...",
        options: [
          "Influence correlation strongly",
          "Never affect summaries",
          "Guarantee causality",
          "Only change labels",
        ],
        correctIndex: 0,
        explanation: "Correlation can be outlier-sensitive.",
      },
      {
        id: "py-m6-l4-q1",
        question: "Which should happen before substantive interpretation?",
        options: [
          "Data-quality audit",
          "Final slide design only",
          "Deleting all missing values",
          "Publishing",
        ],
        correctIndex: 0,
        explanation: "Interpretation depends on data integrity.",
      },
      {
        id: "py-m6-l4-q2",
        question: "What does DataFrame.pipe support?",
        options: [
          "Composable transformation functions",
          "Only plotting",
          "Only joins",
          "Only file export",
        ],
        correctIndex: 0,
        explanation: "pipe applies functions within a readable workflow.",
      },
    ],
  },

  {
    key: "module-07-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 7,
    title: "Module 7 Checkpoint",
    description: "Check your understanding of time series and reproducible workflows.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m7-l1-q1",
        question: "Which function parses a date-like Series?",
        options: [
          "pd.to_datetime",
          "pd.merge",
          "np.std",
          "Path",
        ],
        correctIndex: 0,
        explanation: "to_datetime parses dates and times.",
      },
      {
        id: "py-m7-l1-q2",
        question: "Why can errors='coerce' be useful?",
        options: [
          "It exposes invalid date strings as missing values",
          "It sorts data",
          "It creates joins",
          "It removes time zones",
        ],
        correctIndex: 0,
        explanation: "Failed parses become NaT for inspection.",
      },
      {
        id: "py-m7-l2-q1",
        question: "Which method is designed for calendar-frequency aggregation?",
        options: [
          "resample",
          "merge",
          "melt",
          "astype",
        ],
        correctIndex: 0,
        explanation: "resample groups datetime-indexed data by frequency.",
      },
      {
        id: "py-m7-l2-q2",
        question: "A rolling mean uses...",
        options: [
          "A moving window",
          "Only the first row",
          "A join key",
          "A category code",
        ],
        correctIndex: 0,
        explanation: "Rolling statistics move through neighbouring observations.",
      },
      {
        id: "py-m7-l3-q1",
        question: "A reusable cleaning step should usually be implemented as...",
        options: [
          "A function",
          "A screenshot",
          "A raw-file overwrite",
          "A hidden notebook state",
        ],
        correctIndex: 0,
        explanation: "Functions centralise and test transformation logic.",
      },
      {
        id: "py-m7-l3-q2",
        question: "Configuration is a good place for...",
        options: [
          "Thresholds and paths",
          "Every intermediate DataFrame",
          "Random copied code",
          "Unrelated comments only",
        ],
        correctIndex: 0,
        explanation: "Configuration stores parameters that control execution.",
      },
      {
        id: "py-m7-l4-q1",
        question: "The best first debugging step is often to...",
        options: [
          "Add random code",
          "Reduce the problem to a small failing example",
          "Delete tests",
          "Optimise immediately",
        ],
        correctIndex: 1,
        explanation: "A small example isolates the issue.",
      },
      {
        id: "py-m7-l4-q2",
        question: "Which is a useful analytical invariant?",
        options: [
          "A supposedly unique ID remains unique",
          "Every chart has five colours",
          "The notebook is long",
          "All variables are strings",
        ],
        correctIndex: 0,
        explanation: "Invariants encode important data assumptions.",
      },
    ],
  },

  {
    key: "module-08-checkpoint",
    courseSlug: "python-for-data-analysis",
    type: "module-checkpoint",
    moduleNumber: 8,
    title: "Module 8 Checkpoint",
    description: "Check your understanding of capstone: from raw data to decision-ready analysis.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-m8-l1-q1",
        question: "The analytical unit is...",
        options: [
          "What one row represents",
          "The plotting library",
          "The file extension",
          "The final slide count",
        ],
        correctIndex: 0,
        explanation: "The unit determines how observations should be counted and summarised.",
      },
      {
        id: "py-m8-l1-q2",
        question: "Which issue most threatens revenue totals?",
        options: [
          "Duplicate order IDs",
          "Long column names",
          "Plot title wording",
          "Notebook theme",
        ],
        correctIndex: 0,
        explanation: "Duplicated transactions can double-count revenue.",
      },
      {
        id: "py-m8-l2-q1",
        question: "A capstone pipeline should ideally start from...",
        options: [
          "Raw input data",
          "A manually edited spreadsheet",
          "The final chart",
          "A screenshot",
        ],
        correctIndex: 0,
        explanation: "Reproducibility requires raw inputs and explicit transformations.",
      },
      {
        id: "py-m8-l2-q2",
        question: "Which join validation fits many orders to one customer record?",
        options: [
          "many_to_one",
          "one_to_many from the left perspective only",
          "many_to_many always",
          "one_to_one always",
        ],
        correctIndex: 0,
        explanation: "The left table has many orders per customer; the right should have one customer record.",
      },
      {
        id: "py-m8-l3-q1",
        question: "A region with highest revenue must also have...",
        options: [
          "The highest margin percentage",
          "Not necessarily the highest margin percentage",
          "The most customers always",
          "No missing values",
        ],
        correctIndex: 1,
        explanation: "Scale and efficiency are different metrics.",
      },
      {
        id: "py-m8-l3-q2",
        question: "A strong visual narrative should...",
        options: [
          "Use a small set of purposeful charts",
          "Show every possible chart",
          "Avoid numbers",
          "Ignore data quality",
        ],
        correctIndex: 0,
        explanation: "Each chart should support a specific analytical question.",
      },
      {
        id: "py-m8-l4-q1",
        question: "Which belongs in a professional analysis report?",
        options: [
          "KPI definitions and limitations",
          "Only screenshots",
          "Undocumented manual edits",
          "Causal claims without evidence",
        ],
        correctIndex: 0,
        explanation: "Definitions and limitations are essential for interpretation.",
      },
      {
        id: "py-m8-l4-q2",
        question: "Why record package versions?",
        options: [
          "To support reproducibility",
          "To change the data",
          "To increase revenue",
          "To avoid functions",
        ],
        correctIndex: 0,
        explanation: "Library behaviour can change between versions.",
      },
    ],
  },

  {
    key: "final-assessment",
    courseSlug: "python-for-data-analysis",
    type: "final-assessment",
    title: "Python for Data Analysis Final Assessment",
    description: "A cumulative assessment covering Python workflow design, NumPy, pandas, cleaning, combining data, exploratory analysis, time-aware workflows, reproducibility and the capstone.",
    passingPercentage: 70,
    questions: [
      {
        id: "py-final-m1-l1",
        question: "What should usually happen before calculating a business KPI from a new file?",
        options: [
          "Plot immediately",
          "Audit structure and quality",
          "Rename every column",
          "Delete missing rows",
        ],
        correctIndex: 1,
        explanation: "You need to understand the data before trusting a calculation.",
      },
      {
        id: "py-final-m1-l2",
        question: "Which collection stores key-value pairs?",
        options: [
          "list",
          "dict",
          "tuple",
          "set",
        ],
        correctIndex: 1,
        explanation: "A dictionary maps keys to values.",
      },
      {
        id: "py-final-m1-l3",
        question: "What should a reusable calculation function usually do with its result?",
        options: [
          "Only print it",
          "Return it",
          "Store it globally",
          "Write it to raw data",
        ],
        correctIndex: 1,
        explanation: "Returned values are reusable and testable.",
      },
      {
        id: "py-final-m1-l4",
        question: "Which variable name is clearest?",
        options: [
          "x1",
          "tmp",
          "monthly_revenue",
          "v",
        ],
        correctIndex: 2,
        explanation: "The name communicates analytical meaning.",
      },
      {
        id: "py-final-m2-l1",
        question: "Which library provides ndarray?",
        options: [
          "pandas",
          "NumPy",
          "pathlib",
          "json",
        ],
        correctIndex: 1,
        explanation: "NumPy provides ndarray.",
      },
      {
        id: "py-final-m2-l2",
        question: "A Boolean mask is primarily used to...",
        options: [
          "Rename variables",
          "Filter elements by condition",
          "Read files",
          "Sort dictionaries",
        ],
        correctIndex: 1,
        explanation: "Masks select elements where the condition is True.",
      },
      {
        id: "py-final-m2-l3",
        question: "Which function ignores NaN values when calculating a mean?",
        options: [
          "np.mean",
          "np.nanmean",
          "np.array",
          "np.shape",
        ],
        correctIndex: 1,
        explanation: "np.nanmean is NaN-aware.",
      },
      {
        id: "py-final-m2-l4",
        question: "Which object is recommended for modern NumPy random generation?",
        options: [
          "np.random.default_rng()",
          "open()",
          "pd.Series()",
          "Path()",
        ],
        correctIndex: 0,
        explanation: "default_rng creates a Generator.",
      },
      {
        id: "py-final-m3-l1",
        question: "Which object is two-dimensional?",
        options: [
          "Series",
          "DataFrame",
          "set",
          "Path",
        ],
        correctIndex: 1,
        explanation: "A DataFrame is a labelled 2D table.",
      },
      {
        id: "py-final-m3-l2",
        question: "Which operator combines two pandas Boolean conditions with logical AND?",
        options: [
          "and",
          "&&",
          "&",
          "+",
        ],
        correctIndex: 2,
        explanation: "Use element-wise & with parentheses.",
      },
      {
        id: "py-final-m3-l3",
        question: "Which method is useful for adding columns in a pipeline?",
        options: [
          "assign",
          "head",
          "merge only",
          "shape",
        ],
        correctIndex: 0,
        explanation: "assign returns a DataFrame with new columns.",
      },
      {
        id: "py-final-m3-l4",
        question: "Which function converts a column to numeric with controlled parsing?",
        options: [
          "pd.to_numeric",
          "df.plot",
          "np.merge",
          "Path.rename",
        ],
        correctIndex: 0,
        explanation: "to_numeric handles numeric conversion.",
      },
      {
        id: "py-final-m4-l1",
        question: "Which expression estimates missing proportion by column?",
        options: [
          "df.isna().mean()",
          "df.mean().isna()",
          "df.shape only",
          "df.sort_values()",
        ],
        correctIndex: 0,
        explanation: "Boolean missing indicators average to proportions.",
      },
      {
        id: "py-final-m4-l2",
        question: "Which pandas accessor exposes vectorised string methods?",
        options: [
          ".str",
          ".num",
          ".txt",
          ".cat only",
        ],
        correctIndex: 0,
        explanation: "Series.str provides string operations.",
      },
      {
        id: "py-final-m4-l3",
        question: "A statistically extreme observation should be...",
        options: [
          "Deleted automatically",
          "Investigated before action",
          "Set to the mean",
          "Converted to string",
        ],
        correctIndex: 1,
        explanation: "Extremeness alone does not prove error.",
      },
      {
        id: "py-final-m4-l4",
        question: "In tidy data, one variable usually corresponds to...",
        options: [
          "One column",
          "One file only",
          "One plot",
          "One function",
        ],
        correctIndex: 0,
        explanation: "Tidy data places variables in columns.",
      },
      {
        id: "py-final-m5-l1",
        question: "Which method creates grouped calculations?",
        options: [
          "groupby",
          "merge",
          "melt",
          "read_csv",
        ],
        correctIndex: 0,
        explanation: "groupby performs split-apply-combine.",
      },
      {
        id: "py-final-m5-l2",
        question: "Which function is designed for categorical frequency tables?",
        options: [
          "pd.crosstab",
          "pd.read_csv",
          "np.mean",
          "Path",
        ],
        correctIndex: 0,
        explanation: "crosstab summarises categorical combinations.",
      },
      {
        id: "py-final-m5-l3",
        question: "Which join keeps every row from the left table?",
        options: [
          "inner",
          "left",
          "right only",
          "cross only",
        ],
        correctIndex: 1,
        explanation: "A left join preserves left rows.",
      },
      {
        id: "py-final-m5-l4",
        question: "Which method usually returns the same number of rows as the input?",
        options: [
          "agg",
          "transform",
          "groupby.size only",
          "pivot_table always",
        ],
        correctIndex: 1,
        explanation: "transform aligns group results to original rows.",
      },
      {
        id: "py-final-m6-l1",
        question: "Which summary is often robust to a long right tail?",
        options: [
          "Median",
          "Maximum only",
          "ID mean",
          "File size",
        ],
        correctIndex: 0,
        explanation: "Median is less influenced by extreme values.",
      },
      {
        id: "py-final-m6-l2",
        question: "Which plot is most suitable for two numeric variables?",
        options: [
          "Scatter plot",
          "Pie chart always",
          "Table only",
          "Histogram of labels",
        ],
        correctIndex: 0,
        explanation: "Scatter plots show paired numeric relationships.",
      },
      {
        id: "py-final-m6-l3",
        question: "A correlation coefficient primarily summarises...",
        options: [
          "Linear association",
          "Causal effect",
          "Missingness only",
          "File size",
        ],
        correctIndex: 0,
        explanation: "Correlation is a measure of linear association.",
      },
      {
        id: "py-final-m6-l4",
        question: "Which should happen before substantive interpretation?",
        options: [
          "Data-quality audit",
          "Final slide design only",
          "Deleting all missing values",
          "Publishing",
        ],
        correctIndex: 0,
        explanation: "Interpretation depends on data integrity.",
      },
      {
        id: "py-final-m7-l1",
        question: "Which function parses a date-like Series?",
        options: [
          "pd.to_datetime",
          "pd.merge",
          "np.std",
          "Path",
        ],
        correctIndex: 0,
        explanation: "to_datetime parses dates and times.",
      },
      {
        id: "py-final-m7-l2",
        question: "Which method is designed for calendar-frequency aggregation?",
        options: [
          "resample",
          "merge",
          "melt",
          "astype",
        ],
        correctIndex: 0,
        explanation: "resample groups datetime-indexed data by frequency.",
      },
      {
        id: "py-final-m7-l3",
        question: "A reusable cleaning step should usually be implemented as...",
        options: [
          "A function",
          "A screenshot",
          "A raw-file overwrite",
          "A hidden notebook state",
        ],
        correctIndex: 0,
        explanation: "Functions centralise and test transformation logic.",
      },
      {
        id: "py-final-m7-l4",
        question: "The best first debugging step is often to...",
        options: [
          "Add random code",
          "Reduce the problem to a small failing example",
          "Delete tests",
          "Optimise immediately",
        ],
        correctIndex: 1,
        explanation: "A small example isolates the issue.",
      },
      {
        id: "py-final-m8-l1",
        question: "The analytical unit is...",
        options: [
          "What one row represents",
          "The plotting library",
          "The file extension",
          "The final slide count",
        ],
        correctIndex: 0,
        explanation: "The unit determines how observations should be counted and summarised.",
      },
      {
        id: "py-final-m8-l2",
        question: "A capstone pipeline should ideally start from...",
        options: [
          "Raw input data",
          "A manually edited spreadsheet",
          "The final chart",
          "A screenshot",
        ],
        correctIndex: 0,
        explanation: "Reproducibility requires raw inputs and explicit transformations.",
      },
      {
        id: "py-final-m8-l3",
        question: "A region with highest revenue must also have...",
        options: [
          "The highest margin percentage",
          "Not necessarily the highest margin percentage",
          "The most customers always",
          "No missing values",
        ],
        correctIndex: 1,
        explanation: "Scale and efficiency are different metrics.",
      },
      {
        id: "py-final-m8-l4",
        question: "Which belongs in a professional analysis report?",
        options: [
          "KPI definitions and limitations",
          "Only screenshots",
          "Undocumented manual edits",
          "Causal claims without evidence",
        ],
        correctIndex: 0,
        explanation: "Definitions and limitations are essential for interpretation.",
      },
    ],
  },
];
