import Link from "next/link";
import Icon from "@/components/Icon";
import SectionHeading from "@/components/SectionHeading";
import CourseCard from "@/components/CourseCard";
import PathFinder from "@/components/PathFinder";
import { subjects, levels, courses, pathways } from "@/lib/data";

export default function Home(){return <main>
 <section className="hero"><div className="shell hero-grid"><div><span className="eyebrow">A better way to learn quantitative subjects</span><h1>Learn deeply.<br/>Think clearly.<br/>Go further.</h1><p>Structured learning paths, interactive lessons and expert tutoring in Statistics, Mathematics, Data Science, Bioinformatics and Computer Science—from high school foundations to postgraduate specialisation.</p><div className="hero-actions"><Link className="button" href="/learning">Find my learning path <Icon name="arrow" size={18}/></Link><Link className="button button-outline" href="/subjects">Explore subjects</Link></div><div className="hero-proof"><span><Icon name="check" size={16}/> School to postgraduate</span><span><Icon name="check" size={16}/> Learn independently or with a tutor</span><span><Icon name="globe" size={16}/> Built for global learners</span></div></div><div className="hero-visual"><span className="visual-kicker">One learning ecosystem</span><h2>Where mathematics, data, computing and biology connect.</h2><div className="hero-orbit"><div className="orbit-ring"></div><div className="orbit-core">MAT</div><span className="orbit-item">Statistics</span><span className="orbit-item">Data Science</span><span className="orbit-item">Bioinformatics</span><span className="orbit-item">Computer Science</span></div></div></div></section>
 <div className="trust-strip"><div className="shell trust-inner"><span>High School</span><span>Undergraduate</span><span>Postgraduate</span><span>Career & Casual Learning</span><span>1-to-1 Academic Support</span></div></div>
 <section className="section"><div className="shell"><SectionHeading eyebrow="Explore disciplines" title="Five subjects. Endless ways to connect them." copy="Start with one discipline or move across them as your goals evolve. Every subject has level-specific routes, courses, practice and expert support."/><div className="subject-grid">{subjects.map(s=><Link href={`/subjects/${s.slug}`} key={s.slug} className={`subject-card ${s.accent}`}><span className="subject-symbol">{s.symbol}</span><h3>{s.name}</h3><p>{s.short}</p><div className="card-arrow"><span>{s.eyebrow}</span><Icon name="arrow" size={18}/></div></Link>)}</div></div></section>
 <section className="section soft"><div className="shell"><SectionHeading eyebrow="Choose your level" title="Built around where you are now." copy="The same subject feels very different at school, university and postgraduate level. Your route should reflect that."/><div className="level-grid">{levels.map((l,i)=><Link href={`/learning?level=${l.slug}`} className="level-card" key={l.slug}><span className="num">0{i+1}</span><h3>{l.name}</h3><small>{l.kicker}</small><p>{l.copy}</p></Link>)}</div></div></section>
 <section className="section"><div className="shell"><PathFinder/></div></section>
 <section className="section"><div className="shell"><SectionHeading eyebrow="Popular courses" title="Start with something worth finishing." copy="Focused, coherent courses with explanations, worked examples, practice and a clear sense of progress."/><div className="course-grid">{courses.filter(c=>c.featured).slice(0,6).map(c=><CourseCard course={c} key={c.slug}/>)}</div><div style={{marginTop:28}}><Link href="/courses" className="button button-outline">Browse all courses <Icon name="arrow" size={17}/></Link></div></div></section>
 <section className="section dark"><div className="shell labs-showcase"><div><SectionHeading eyebrow="Interactive Labs" title="Don’t just watch. Learn by doing." copy="Manipulate models, distributions, algorithms and biological data concepts directly. Build intuition before memorising formulas."/><Link href="/labs" className="button button-white">Explore interactive labs <Icon name="arrow" size={17}/></Link></div><div className="lab-visual"><span className="eyebrow">Live concept · Sampling distributions</span><h3 style={{font:"700 30px Georgia",margin:"10px 0"}}>See uncertainty take shape.</h3><p style={{color:'#6a665e'}}>Adjust sample size and observe how the sampling distribution changes.</p><div className="chart-demo"><span></span><span></span><span></span><span></span><span></span></div></div></div></section>
 <section className="section"><div className="shell"><SectionHeading eyebrow="Guided pathways" title="Know where you are going, not just what comes next." copy="Pathways connect individual courses into purposeful journeys for careers, university study and research."/><div className="pathway-grid">{pathways.map(p=><Link href={`/pathways/${p.slug}`} className="pathway-card" key={p.slug}><div className="top"><span className="eyebrow">{p.tag}</span><span>{p.duration}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="pathway-steps">{p.steps.map((_,i)=><span key={i}></span>)}</div><b>Explore pathway →</b></Link>)}</div></div></section>
 <section className="section soft"><div className="shell"><div className="testimonial"><div className="quote-mark">“</div><div><blockquote>Learn independently when you can. Get expert help exactly when you need it.</blockquote><cite>That is the principle behind My Academic Tutor: structured self-learning with serious human academic support available in the same place.</cite></div></div></div></section>
 <section className="section"><div className="shell"><div className="cta-band"><div><span className="eyebrow light">Ready when you are</span><h2>Build a learning plan that fits your goal.</h2><p>Choose a subject and level, then follow a clear pathway—or work with a tutor for personalised support.</p></div><div className="hero-actions"><Link href="/learning" className="button button-white">Start learning</Link><Link href="/tutoring" className="button" style={{borderColor:'#555'}}>Find a tutor</Link></div></div></div></section>
 </main>}
