import type {
  LessonContent,
} from "../types";


export const statisticsFoundationsModule06:
  LessonContent[] = [

  /* ========================================================================
     LESSON 21
     ======================================================================== */

  {
    courseSlug:
      "statistics-foundations",

    lessonKey:
      "m6-l1-confidence-intervals",

    title:
      "From an estimate to an interval",

    subtitle:
      "A sample estimate is useful, but an interval tells us how uncertain that estimate is.",

    estimatedMinutes:
      35,

    objectives: [
      "Distinguish a point estimate from an interval estimate.",
      "Explain why sample estimates require uncertainty.",
      "Interpret standard error as a measure of precision.",
      "Understand the basic structure estimate plus or minus uncertainty.",
      "Explain the meaning of margin of error.",
    ],

    content: [

      {
        type:
          "paragraph",

        text:
          "Suppose a random sample produces a mean of 72. Reporting 72 alone hides an important fact: a different random sample would probably produce a slightly different mean.",
      },

      {
        type:
          "heading",

        text:
          "Point estimates",
      },

      {
        type:
          "paragraph",

        text:
          "A point estimate is a single sample statistic used to estimate a population parameter. A sample mean can estimate a population mean, and a sample proportion can estimate a population proportion.",
      },

      {
        type:
          "callout",

        title:
          "Point estimate",

        text:
          "A point estimate gives our best single-number estimate from the observed sample.",
      },

      {
        type:
          "heading",

        text:
          "Why one number is not enough",
      },

      {
        type:
          "paragraph",

        text:
          "Because sample statistics vary across repeated samples, we should also communicate how precise the estimate is.",
      },

      {
        type:
          "paragraph",

        text:
          "An estimate based on 2,000 observations will often be more precise than the same type of estimate based on 20 observations.",
      },

      {
        type:
          "heading",

        text:
          "Standard error",
      },

      {
        type:
          "paragraph",

        text:
          "The standard error describes how much a statistic would vary across repeated samples generated by the same sampling process.",
      },

      {
        type:
          "callout",

        title:
          "Precision",

        text:
          "Smaller standard error means greater repeated-sample precision.",
      },

      {
        type:
          "heading",

        text:
          "From a point to an interval",
      },

      {
        type:
          "paragraph",

        text:
          "A confidence interval expands the point estimate into a range of values by allowing for sampling uncertainty.",
      },

      {
        type:
          "callout",

        title:
          "Basic structure",

        text:
          "Confidence interval = estimate ± margin of error.",
      },

      {
        type:
          "heading",

        text:
          "Margin of error",
      },

      {
        type:
          "paragraph",

        text:
          "The margin of error depends on how variable the estimate is and how much confidence we want the interval procedure to provide.",
      },

      {
        type:
          "paragraph",

        text:
          "More precise estimates have smaller standard errors and therefore tend to produce narrower intervals.",
      },

      {
        type:
          "heading",

        text:
          "Precision is not the same as accuracy",
      },

      {
        type:
          "paragraph",

        text:
          "A confidence interval describes sampling uncertainty under the assumed study design and model. It does not automatically protect against selection bias, measurement error or inappropriate assumptions.",
      },

      {
        type:
          "callout",

        title:
          "Remember Module 5",

        text:
          "A very narrow confidence interval around a biased estimate can still give a confidently wrong answer.",
      },

    ],

    workedExamples: [

      {
        title:
          "A sample mean",

        question:
          "A random sample estimates average weekly study time as 11.8 hours with margin of error 1.4 hours. Construct the interval.",

        steps: [
          "Start with the estimate: 11.8.",
          "Subtract the margin of error: 11.8 − 1.4 = 10.4.",
          "Add the margin of error: 11.8 + 1.4 = 13.2.",
        ],

        answer:
          "The confidence interval is 10.4 to 13.2 hours.",
      },

      {
        title:
          "Comparing precision",

        question:
          "Study A gives 50 ± 2, while Study B gives 50 ± 8. Which is more precise?",

        steps: [
          "Both studies have the same point estimate.",
          "Study A has the smaller margin of error.",
          "Its interval is therefore narrower.",
        ],

        answer:
          "Study A provides the more precise estimate.",
      },

    ],

    exercises: [

      {
        question:
          "An estimate is 42 with margin of error 5. Find the confidence interval.",

        answer:
          "42 − 5 = 37 and 42 + 5 = 47, so the interval is 37 to 47.",
      },

      {
        question:
          "Which estimate is more precise: 20 ± 1.5 or 20 ± 6?",

        answer:
          "20 ± 1.5 is more precise because its interval is narrower.",
      },

      {
        question:
          "Why can a narrow interval still be misleading?",

        answer:
          "A narrow interval reflects precision under the assumed sampling process but does not automatically remove bias or measurement problems.",
      },

    ],

    quiz: [

      {
        question:
          "What is a point estimate?",

        options: [
          "A range of plausible values",
          "A single sample statistic used to estimate a parameter",
          "The population itself",
          "A guarantee that the estimate is correct",
        ],

        correctIndex:
          1,

        explanation:
          "A point estimate is a single-number estimate calculated from sample data.",
      },

      {
        question:
          "What does a smaller standard error generally indicate?",

        options: [
          "Greater precision",
          "Greater bias",
          "A larger population",
          "No uncertainty",
        ],

        correctIndex:
          0,

        explanation:
          "Smaller repeated-sample variability corresponds to greater precision.",
      },

      {
        question:
          "What is the basic form of a confidence interval?",

        options: [
          "Estimate ± margin of error",
          "Population × sample size",
          "Mean ÷ median",
          "p-value ± variance",
        ],

        correctIndex:
          0,

        explanation:
          "A confidence interval combines a point estimate with an allowance for uncertainty.",
      },

    ],

    summary: [
      "A point estimate gives a single sample-based estimate of a population parameter.",
      "Sample estimates carry uncertainty because they vary across repeated samples.",
      "Standard error measures repeated-sample variability of an estimate.",
      "Confidence intervals combine an estimate with a margin of error.",
      "Narrower intervals generally represent greater precision.",
      "Precision does not automatically protect against systematic bias.",
    ],

    nextStep:
      "Next, we examine how confidence intervals are constructed from an estimate, a standard error and a critical value.",
  },


  /* ========================================================================
     LESSON 22
     ======================================================================== */

  {
    courseSlug:
      "statistics-foundations",

    lessonKey:
      "m6-l2-confidence-intervals",

    title:
      "Building confidence intervals",

    subtitle:
      "Confidence intervals combine an estimate, its standard error and a critical value.",

    estimatedMinutes:
      40,

    objectives: [
      "Identify the estimate, standard error and critical value in a confidence interval.",
      "Construct simple confidence intervals.",
      "Explain how sample size changes interval width.",
      "Explain how confidence level changes interval width.",
      "Compare precision across confidence intervals.",
    ],

    content: [

      {
        type:
          "paragraph",

        text:
          "Many confidence intervals can be understood using the same broad structure: estimate plus or minus a critical value multiplied by the standard error.",
      },

      {
        type:
          "callout",

        title:
          "General form",

        text:
          "estimate ± critical value × standard error.",
      },

      {
        type:
          "heading",

        text:
          "The estimate",
      },

      {
        type:
          "paragraph",

        text:
          "The estimate is the sample statistic at the centre of the interval. For a population mean, this may be the sample mean. For a population proportion, it may be the sample proportion.",
      },

      {
        type:
          "heading",

        text:
          "The standard error",
      },

      {
        type:
          "paragraph",

        text:
          "The standard error quantifies how much the statistic would vary across repeated samples.",
      },

      {
        type:
          "heading",

        text:
          "The critical value",
      },

      {
        type:
          "paragraph",

        text:
          "The critical value determines how many standard errors are placed on either side of the estimate.",
      },

      {
        type:
          "paragraph",

        text:
          "For a standard normal approximation, a 95% confidence interval commonly uses approximately 1.96 standard errors on each side.",
      },

      {
        type:
          "heading",

        text:
          "Sample size affects width",
      },

      {
        type:
          "paragraph",

        text:
          "Larger samples generally reduce the standard error, producing narrower intervals when other features remain unchanged.",
      },

      {
        type:
          "callout",

        title:
          "More data",

        text:
          "Larger sample size generally increases precision, but with diminishing returns because standard error changes with the square root of n.",
      },

      {
        type:
          "heading",

        text:
          "Confidence level affects width",
      },

      {
        type:
          "paragraph",

        text:
          "Increasing the confidence level requires a larger critical value. This widens the confidence interval.",
      },

      {
        type:
          "bullets",

        items: [
          "90% confidence → narrower interval.",
          "95% confidence → wider than 90%.",
          "99% confidence → wider again.",
        ],
      },

      {
        type:
          "callout",

        title:
          "Trade-off",

        text:
          "Greater confidence requires a wider interval when the data and sample size stay fixed.",
      },

    ],

    workedExamples: [

      {
        title:
          "Constructing a 95% interval",

        question:
          "A sample mean is 80 and its standard error is 3. Using critical value 1.96, construct the interval.",

        steps: [
          "Calculate the margin of error: 1.96 × 3 = 5.88.",
          "Lower limit: 80 − 5.88 = 74.12.",
          "Upper limit: 80 + 5.88 = 85.88.",
        ],

        answer:
          "The approximate 95% confidence interval is 74.12 to 85.88.",
      },

      {
        title:
          "Increasing sample size",

        question:
          "Why will increasing n from 25 to 100 usually make a confidence interval narrower?",

        steps: [
          "The standard error of a mean is proportional to 1/√n.",
          "Increasing n from 25 to 100 doubles √n.",
          "The standard error therefore roughly halves.",
          "With the same critical value, the margin of error roughly halves.",
        ],

        answer:
          "The larger sample reduces the standard error and therefore narrows the interval.",
      },

    ],

    exercises: [

      {
        question:
          "Estimate = 30, SE = 2 and critical value = 1.96. Find the margin of error.",

        answer:
          "1.96 × 2 = 3.92.",
      },

      {
        question:
          "Using the previous result, construct the interval.",

        answer:
          "30 − 3.92 = 26.08 and 30 + 3.92 = 33.92.",
      },

      {
        question:
          "If everything else remains unchanged, which is wider: a 90% or 99% confidence interval?",

        answer:
          "The 99% confidence interval because greater confidence requires a larger critical value.",
      },

    ],

    quiz: [

      {
        question:
          "What happens to interval width when the standard error decreases?",

        options: [
          "It generally becomes narrower",
          "It always becomes wider",
          "It becomes a p-value",
          "Nothing changes",
        ],

        correctIndex:
          0,

        explanation:
          "Smaller standard error reduces the margin of error.",
      },

      {
        question:
          "What happens when confidence level increases from 90% to 99%?",

        options: [
          "The critical value generally increases",
          "The critical value becomes zero",
          "The estimate disappears",
          "The sample size automatically doubles",
        ],

        correctIndex:
          0,

        explanation:
          "Higher confidence requires a larger critical value.",
      },

      {
        question:
          "Which component lies at the centre of the confidence interval?",

        options: [
          "The point estimate",
          "The confidence level",
          "The sample size",
          "The population size",
        ],

        correctIndex:
          0,

        explanation:
          "The confidence interval is centred on the sample estimate in this standard construction.",
      },

    ],

    summary: [
      "Many confidence intervals follow estimate ± critical value × standard error.",
      "The estimate forms the centre of the interval.",
      "The standard error measures sampling precision.",
      "Larger samples generally reduce standard error and narrow intervals.",
      "Higher confidence levels require larger critical values and wider intervals.",
      "Confidence level and precision involve a trade-off.",
    ],

    nextStep:
      "Next, we focus on what confidence intervals actually mean—and several very common interpretations that are incorrect.",
  },


  /* ========================================================================
     LESSON 23
     ======================================================================== */

  {
    courseSlug:
      "statistics-foundations",

    lessonKey:
      "m6-l3-confidence-intervals",

    title:
      "Interpreting confidence intervals correctly",

    subtitle:
      "The meaning of a confidence interval comes from repeated sampling, not from assigning probability to a fixed parameter after the interval is observed.",

    estimatedMinutes:
      45,

    objectives: [
      "Interpret confidence level using repeated sampling.",
      "Avoid common confidence-interval misconceptions.",
      "Explain what interval width says about precision.",
      "Distinguish confidence level from probability assigned to a fixed parameter.",
      "Recognise limitations of confidence intervals.",
    ],

    content: [

      {
        type:
          "heading",

        text:
          "What does 95% confidence mean?",
      },

      {
        type:
          "paragraph",

        text:
          "Imagine repeatedly drawing samples using the same method and constructing a 95% confidence interval after every sample. In the long run, approximately 95% of those intervals would contain the true parameter if the assumptions are satisfied.",
      },

      {
        type:
          "callout",

        title:
          "Repeated-sampling interpretation",

        text:
          "The 95% refers to the long-run success rate of the interval-producing procedure.",
      },

      {
        type:
          "heading",

        text:
          "The parameter is not repeatedly moving",
      },

      {
        type:
          "paragraph",

        text:
          "In the frequentist interpretation used here, the population parameter is treated as fixed. The intervals vary from sample to sample.",
      },

      {
        type:
          "paragraph",

        text:
          "Once a particular interval has been calculated, that interval either contains the parameter or it does not.",
      },

      {
        type:
          "heading",

        text:
          "A common incorrect statement",
      },

      {
        type:
          "callout",

        title:
          "Do not say",

        text:
          "There is a 95% probability that the fixed population parameter lies inside this particular observed interval.",
      },

      {
        type:
          "paragraph",

        text:
          "That wording does not match the standard frequentist interpretation. The confidence level refers to the procedure before observing which particular interval is produced.",
      },

      {
        type:
          "heading",

        text:
          "What interval width tells us",
      },

      {
        type:
          "paragraph",

        text:
          "A narrow confidence interval usually indicates a more precise estimate than a wide interval, assuming the intervals concern comparable quantities.",
      },

      {
        type:
          "heading",

        text:
          "Confidence intervals and plausible values",
      },

      {
        type:
          "paragraph",

        text:
          "In applied interpretation, values inside the interval are often described as values reasonably compatible with the data and model at the specified confidence level.",
      },

      {
        type:
          "paragraph",

        text:
          "That does not mean every value inside the interval is equally supported or that values outside the interval are impossible.",
      },

      {
        type:
          "heading",

        text:
          "Confidence intervals do not fix poor studies",
      },

      {
        type:
          "paragraph",

        text:
          "Coverage claims rely on the sampling design, statistical model and assumptions being appropriate. Selection bias, confounding, measurement error or incorrect modelling can make a mathematically correct interval scientifically misleading.",
      },

      {
        type:
          "confidence-interval-simulator",

        title:
          "Confidence Interval Coverage Simulator",

        description:
          "Generate repeated intervals and watch some miss the true population mean. Change n and the confidence level to see how precision and coverage behave.",
      },

      {
        type:
          "heading",

        text:
          "What to investigate in the simulator",
      },

      {
        type:
          "bullets",

        items: [
          "Generate 100 intervals at 95% confidence.",
          "Notice that a few intervals usually miss the true mean.",
          "Increase the sample size and compare interval widths.",
          "Change from 90% to 99% confidence and compare widths.",
          "Repeat the simulation and notice that the exact observed coverage varies from run to run.",
        ],
      },

      {
        type:
          "callout",

        title:
          "Key distinction",

        text:
          "Confidence level describes long-run coverage. Interval width describes precision. They are related but not the same thing.",
      },

    ],

    workedExamples: [

      {
        title:
          "Interpreting a reported interval",

        question:
          "A study reports a 95% confidence interval of 12.4 to 18.1. Which interpretation is appropriate?",

        steps: [
          "The interval was produced by a statistical procedure with a nominal 95% long-run coverage rate under its assumptions.",
          "The fixed parameter is not treated as having a 95% chance of changing location.",
          "The observed interval can be described as a range of values compatible with the data under the stated model.",
        ],

        answer:
          "A suitable interpretation refers to the 95% long-run coverage of the method and treats 12.4 to 18.1 as the interval produced from this sample.",
      },

      {
        title:
          "Comparing two intervals",

        question:
          "Study A reports 10 to 20. Study B reports 14 to 16 for the same type of parameter at the same confidence level. Which is more precise?",

        steps: [
          "Compare interval widths.",
          "Study A has width 10.",
          "Study B has width 2.",
        ],

        answer:
          "Study B is more precise because its confidence interval is much narrower.",
      },

    ],

    exercises: [

      {
        question:
          "Why do approximately 5% of 95% confidence intervals miss the true parameter in repeated sampling?",

        answer:
          "Because the procedure is designed for approximately 95% long-run coverage, leaving approximately 5% that do not contain the parameter under the model.",
      },

      {
        question:
          "Does a value outside a 95% confidence interval have zero probability of being the true parameter?",

        answer:
          "No. The frequentist interval does not assign zero probability to individual parameter values outside the observed interval.",
      },

      {
        question:
          "What generally happens to interval width when sample size increases?",

        answer:
          "The interval usually becomes narrower because the standard error decreases.",
      },

    ],

    quiz: [

      {
        question:
          "What does 95% confidence refer to?",

        options: [
          "A 95% probability that the fixed parameter changes location",
          "The long-run coverage rate of the interval procedure",
          "95% of observations lying inside the interval",
          "A guarantee that every interval contains the parameter",
        ],

        correctIndex:
          1,

        explanation:
          "The confidence level describes long-run performance across repeated samples.",
      },

      {
        question:
          "What usually indicates greater precision?",

        options: [
          "A wider interval",
          "A narrower interval",
          "A larger p-value",
          "A smaller population",
        ],

        correctIndex:
          1,

        explanation:
          "Narrower intervals indicate less sampling uncertainty when comparing like quantities.",
      },

      {
        question:
          "Which statement is correct?",

        options: [
          "Every 95% confidence interval contains the parameter",
          "Approximately 95% of intervals from repeated use of the procedure contain the parameter under the assumptions",
          "95% of population observations must lie inside every confidence interval",
          "Confidence intervals remove selection bias",
        ],

        correctIndex:
          1,

        explanation:
          "Confidence refers to the long-run success rate of the interval construction procedure.",
      },

      {
        question:
          "Can a confidence interval be misleading if the sample is severely biased?",

        options: [
          "No",
          "Yes",
          "Only if n is below 10",
          "Only if the interval is wide",
        ],

        correctIndex:
          1,

        explanation:
          "A confidence interval quantifies sampling uncertainty under assumptions; it cannot automatically correct systematic bias.",
      },

    ],

    summary: [
      "Confidence level describes the long-run coverage of an interval-producing procedure.",
      "The population parameter is treated as fixed while intervals vary between samples.",
      "A 95% confidence interval should not automatically be described as giving a 95% probability to a fixed parameter after the interval is observed.",
      "Narrower intervals generally indicate greater precision.",
      "Higher confidence requires wider intervals when the data stay fixed.",
      "Confidence intervals rely on appropriate sampling, modelling and assumptions.",
    ],

    nextStep:
      "Module 7 completes the course by introducing hypothesis testing, p-values and responsible statistical conclusions.",
  },

];